In [5]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [6]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:

构造一个5×3的矩阵，未初始化


In [7]:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00  0.0000e+00 -2.6038e+20
 4.5675e-41 -2.6040e+20  4.5675e-41
-2.8624e+28  4.5675e-41 -2.8624e+28
 4.5675e-41 -3.3977e+28  4.5675e-41
-3.3128e+28  4.5675e-41 -1.1056e+21
[torch.FloatTensor of size 5x3]



Construct a randomly initialized matrix

构造一个随机初始化的矩阵



In [8]:
x = torch.rand(5, 3)
print(x)


 0.5539  0.6160  0.0284
 0.7115  0.8396  0.0383
 0.0016  0.5399  0.2294
 0.9400  0.6089  0.3219
 0.5743  0.8056  0.9103
[torch.FloatTensor of size 5x3]



Get its size



In [9]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports the same operations

实际上是一个元祖，支持内置的运算
</p></div>


Operations
^^^^^^^^^^
There are multiple syntaxes for operations. Let's see addition as an example

Addition: syntax 1



In [10]:
y = torch.rand(5, 3)
print(x + y)


 0.8819  0.6414  0.1551
 1.4075  1.1267  0.3612
 0.9549  1.1729  0.9335
 1.8810  1.2767  1.0070
 0.6508  1.5673  1.8075
[torch.FloatTensor of size 5x3]



Addition: syntax 2



In [11]:
print(torch.add(x, y))


 0.8819  0.6414  0.1551
 1.4075  1.1267  0.3612
 0.9549  1.1729  0.9335
 1.8810  1.2767  1.0070
 0.6508  1.5673  1.8075
[torch.FloatTensor of size 5x3]



Addition: giving an output tensor



In [ ]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

Addition: in-place

相当于+=



In [12]:
# adds x to y
y.add_(x)
print(y)


 0.8819  0.6414  0.1551
 1.4075  1.1267  0.3612
 0.9549  1.1729  0.9335
 1.8810  1.2767  1.0070
 0.6508  1.5673  1.8075
[torch.FloatTensor of size 5x3]



<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.
    带下划线的操作都会改变自身
    </p></div>

You can use standard numpy-like indexing with all bells and whistles!



In [13]:
print(x[:, 1])


 0.6160
 0.8396
 0.5399
 0.6089
 0.8056
[torch.FloatTensor of size 5]



**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc are described
  `here <http://pytorch.org/docs/torch>`_

Numpy Bridge
------------

torch的tensor 到 numpy的array 使用 .numpy()方法

numpy的array 到 torch的tensor 使用 .from_numpy()方法

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory
locations, and changing one will change the other.

torch 里面的 Tensor 和 numpy 里面的 array 会共享内存，改变其中一个会随之改变另一个

Converting torch Tensor to numpy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [15]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [16]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.



In [17]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


Converting numpy Array to torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the torch Tensor automatically



In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

除了字符张量（CharTensor)，在CPU里面的张量都支持与numpy里的相互转换

CUDA Tensors
------------

Tensors can be moved onto GPU using the ``.cuda`` function.

张量可以加载到GPU上使用 .cuda（） 函数



In [28]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    print(z)
    


 1.4358  1.2573  0.1834
 2.1190  1.9662  0.3996
 0.9565  1.7129  1.1629
 2.8210  1.8856  1.3290
 1.2250  2.3730  2.7178
[torch.cuda.FloatTensor of size 5x3 (GPU 0)]

